spring:
  application:
    name: product
  config:
    import:
      - optional:configserver:http://configserver:8880/

  datasource:
    url: jdbc:mysql://mysql:3306/ms_product
    username: root
    password: ucb2024  # Cambia la contraseña aquí
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 9091  # O 9091 para ms-product2
  error:
    include-messages: always

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs
  packages-to-scan: com.example.product
  paths-to-match: /**

api:
  responseCodes:
    okDescription: OK
    badRequestDescription: "Solicitud incorrecta, formato inválido de la solicitud. Consulte el mensaje de respuesta para más información."
    internalServerErrorDescription: "Error interno del servidor. Consulte el mensaje de respuesta para más información."

management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: debug
    com.example.product: info  # Controla el nivel de log para el paquete específico
  pattern:
    level: "5%p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
